#!/usr/bin/env bash
set -ex

function usage() {
    echo -n \
    "Usage: $(basename "$0")
Build application for TravisCI.
"
}

function cibuild() {
    ./scripts/setup
    ./scripts/lint
    ./scripts/test
    ./scripts/test --git
    npm run bundle
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]; then
    if [ "${1:-}" = "--help" ]; then
        usage
    else
        cibuild
    fi
fi
